{% set name = "multitasking" %}
{% set version = "0.0.9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "b59d99f709d2e17d60ccaa2be09771b6e9ed9391c63f083c0701e724f624d2e0"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - multitasking

about:
  home: "https://github.com/ranaroussi/multitasking"
  license: "Apache Software"
  license_family: "APACHE"
  license_file: ""
  summary: "Non-blocking Python methods using decorators"
  description: |
    MultiTasking is a tiny Python library lets you convert your Python methods
    into asynchronous, non-blocking methods by using a aimple decorator.
  doc_url: "https://github.com/ranaroussi/multitasking"
  dev_url: "https://pypi.python.org/pypi/multitasking"
  doc_source_url: https://github.com/ranaroussi/multitasking/blob/master/README.rst

extra:
  recipe-maintainers:
    - ranaroussi
